#!/bin/sh

function pause(){
   read -p "$*"
}

. /etc/default/get_iplayer_web_pvr
/usr/share/get_iplayer/launchwindow &
/usr/bin/perl /usr/share/get_iplayer/get_iplayer.cgi -p $PORT -g /usr/bin/get_iplayer -l $LISTEN
pause 'Press [Enter] key to continue...'
